---
- hosts: dockerinstance
  remote_user: root
  tasks:
  - name: deploy applicaiton as docker container
    docker_container:
      name: springbootapplication
      image: naresh240/hellospringboot:{{ ImageTag }}
      state: started
      ports:
       - "8888:8080"
    tags: create
  - name: stop container
    docker_container:
      name: springbootapplication
      image: naresh240/hellospringboot:{{ ImageTag }}
      state: absent
    tags: remove
