---
- hosts: dockerinstance
  tasks:
  - name: Install pip
    yum:
      name: python-pip
      state: present
  - name: Install docker
    yum:
      name: docker
      state: present
  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true
