---
- hosts: dockerinstance
  tasks:
  - name: Install pip
    yum:
      name: python-pip
      state: present
  - name: Install docker
    pip:
      name: docker
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: deploy applicaiton as docker container
    docker_container:
      name: springbootapplication
      image: naresh240/springboohello:{{ ImageTag }}
      state: started
      ports:
       - "8080:8080"
