---
- hosts: dockerinstance
  become: yes
  tasks:
  - name: install docker
    package:
      name: docker-ce
      state: present
  - name: start docker service
    service:
      name: docker
      state: started
  - name: deploy applicaiton as docker container
    docker_container:
      name: springbootapplication
      image: naresh240/springboohello:{{ ImageTag }}
      state: started
      ports:
       - "8888:8888"
    tags: create
  - name: stop container
    docker_container:
      name: springbootapplication
      image: naresh240/springboohello:{{ ImageTag }}
      state: absent
    tags: remove
