---
- hosts: dockerinstance
  remote_user: jenkins
  become: yes
  become_method: sudo
  tasks:
    - name: install docker
      yum: name=docker

    **- name: Ensure service is enabled
      command: service docker restart***

    - name: copying file to remote
      copy:
        src: ./docker
        dest: /home/jenkins/docker
  - name: deploy applicaiton as docker container
    docker_container:
      name: springbootapplication
      image: naresh240/springboohello:{{ ImageTag }}
      state: started
      ports:
       - "8888:8888"
    tags: create
  - name: stop container
    docker_container:
      name: springbootapplication
      image: naresh240/springboohello:{{ ImageTag }}
      state: absent
    tags: remove
